Nueva Clase Avestruz
reyniergt/learn-java pull request #1
Opened 2019-08-29 01:54 UTC by elizaochoa86

2019-09-24 20:36 UTC, reyniergt commented on src/main/java/com/learn/java/inheritance/AbstractFlyer.java
> +        System.out.println(1);
modify the fly method in order to receive an argument _flyer_ and print "the _flyer_ flies"

2019-09-24 20:37 UTC, reyniergt commented on src/main/java/com/learn/java/inheritance/AbstractRunner.java
> +        System.out.println(2);
modify the run method in order to receive an argument runner and print "the _runner_ runs"

2019-09-24 20:38 UTC, reyniergt commented on src/main/java/com/learn/java/inheritance/AbstractSwimmer.java
> +        System.out.println(3);
modify the run method in order to receive an argument _swimmer_ and print "the _swimmer_ swims"

2019-09-24 20:39 UTC, reyniergt commented on src/main/java/com/learn/java/inheritance/Cat.java
> +
declare a constant runner with value Cat and pass it to the run method

2019-09-24 20:44 UTC, reyniergt commented on src/main/java/com/learn/java/inheritance/Dog.java
> +
assign the value Dog to the runner field

2019-09-24 20:44 UTC, reyniergt commented on src/main/java/com/learn/java/inheritance/Dolphin.java
> +
assign the value Dolphin to the _swimmer_ field

2019-09-24 20:47 UTC, reyniergt requested changes
verify comments

2019-09-26 16:04 UTC, elizaochoa86 commented
Changes are reading!

2019-09-26 23:36 UTC, reyniergt approved these changes
**Great work!!**

2019-09-26 23:53 UTC, merged